# Generated by Django 2.1.7 on 2019-03-11 12:37

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_auto_20190308_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexpense',
            name='paidby',
            field=models.CharField(max_length=300, verbose_name=django.contrib.auth.models.User),
        ),
    ]
